version: '3'
services:
  frontend:
    build:
      context: ./Rspace_frontend
      dockerfile: Dockerfile
    ports:
      - 3333:80

  backend:
    build:
      context: ./Rspace_backend
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - db
      - redis  # 添加Redis服务依赖
  db:
    image: mysql:8.0
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c316cb46aefed2fd80df56643cec2585
      MYSQL_DATABASE: rspace
      MYSQL_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
  redis:  # 添加Redis服务
    image: redis
    ports:
      - 6379:6379

    #volumes:
      #- ./redis-data:/data
